kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
  - ls > msg.txt

- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 
      from_secret: bot_token
    to:
      from_secret: tg_l2_user_id
   message_file: msg.txt
